language: ruby
notifications:
  irc: "chat.freenode.net#projectvov"
before_script:
  - bundle install
  - bundle exec rake setup:configs
  - bundle exec rake db:migrate
script: bundle exec rspec
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
