version: 2.1
orbs:
  ruby: circleci/ruby@0.2.1 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7-stretch
    executor: ruby/default
    parameters:
      bundler_version:
        type: string
        default: '2.0.2'
    steps:
      - checkout
      - ruby/load-cache
      - run:
          name: Update bundler
          command: |
            echo 'export BUNDLER_VERSION=<< parameters.bundler_version >>' >> $BASH_ENV
            gem install bundler -v << parameters.bundler_version >>
      - ruby/install-deps
      - ruby/save-cache
      - run:
          command: bundle exec rake setup:configs
      - run:
          command: bundle exec rake db:migrate
      - ruby/run-tests
