# Builds image and stores in ghcr.io then sends webhook to deploy new image to timeliner.dlib.indiana.edu
name: Podman Image CI

on:
  push:
    branches: [ "development", "main" ]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/avalonmediasystem
  IMAGE_TAG: ${{ fromJSON('{"refs/heads/development":"staging","refs/heads/main":"production"}')[github.ref] }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - name: Yarn install
      run: yarn install --frozen-lockfile # optional, --immutable
    - name: Yarn build
      # Explicitly set CI to false to avoid elevating warnings to errors
      run: CI=false yarn build
    - name: Build Image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: switchyard
        tags: ${{ env.IMAGE_TAG }} ${{ github.sha }}
        containerfiles: ./Dockerfile
        extra-args: --target production
        oci: true
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
